import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import { ChildProps } from "@/types";
import Navbar from "@/components/shared/navbar";
import { Toaster } from "@/components/ui/toaster";

const montserrat = Montserrat({
  weight: ["400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Seleor E-Commerce",
  description: "Generated by create next app | Jasurbek",
  icons: {
    icon: "/favicon.png",
  },
};

function RootLayout({ children }: ChildProps) {
  return (
    <html lang="en">
      <body className={`${montserrat.className} antialiased`}>
        <Navbar />
        <div className="container mt-24 max-w-6xl">{children}</div>
        <Toaster />
      </body>
    </html>
  );
}

export default RootLayout;
